name = "vii-ink-waline"
main = "src/index.ts"
compatibility_date = "2026-06-01"
workers_dev = true

[[routes]]
pattern = "waline1.ficor.cc"
custom_domain = true

[vars]
SITE_URL = "https://vii.ink"
ADMIN_NICK = "Ficor"
ADMIN_EMAIL = "ficor@qq.com"
ADMIN_URL = "https://vii.ink"

[[d1_databases]]
binding = "DB"
database_name = "vii-ink-waline"
database_id = "fed0ca8e-25b8-49a9-a6ca-8d77767fa380"
